services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - .data/redis:/data
    command: redis-server --port 6379
    ports:
      - "6379:6379"

networks:
  default:
    name: spring-coupon-practice
