name: Test

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 1. Set up jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 2. Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 3. Test with gradle
        run: ./gradlew clean test